// <auto-generated />
using System;
using DataAccessLayer.Concrete;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataAccessLayer.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20231215015612_mig1")]
    partial class mig1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EntityLayer.Concrete.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryID");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Firmalar", b =>
                {
                    b.Property<int>("FirmaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirmaAd")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FirmaID");

                    b.ToTable("Firmalars");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Hareketler", b =>
                {
                    b.Property<int>("HareketID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("FirmaID")
                        .HasColumnType("int");

                    b.Property<int>("FirmaPuan")
                        .HasColumnType("int");

                    b.Property<string>("FirmaYorum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FirmalarFirmaID")
                        .HasColumnType("int");

                    b.Property<int>("OyunID")
                        .HasColumnType("int");

                    b.Property<int?>("OyunlarOyunID")
                        .HasColumnType("int");

                    b.Property<int>("Platformid")
                        .HasColumnType("int");

                    b.HasKey("HareketID");

                    b.HasIndex("FirmalarFirmaID");

                    b.HasIndex("OyunlarOyunID");

                    b.HasIndex("Platformid");

                    b.ToTable("Hareketlers");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Oyunlar", b =>
                {
                    b.Property<int>("OyunID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<string>("GelisticiFirma")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OyunAciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OyunAd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OyunCikisTarih")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("OyunFiyat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("OyunGenelPuan")
                        .HasColumnType("int");

                    b.Property<string>("OyunResim")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OyunTanitim")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Platformid")
                        .HasColumnType("int");

                    b.HasKey("OyunID");

                    b.HasIndex("CategoryID");

                    b.HasIndex("Platformid");

                    b.ToTable("Oyunlars");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Platform", b =>
                {
                    b.Property<int>("Platformid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("PlatformAd")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Platformid");

                    b.ToTable("Platforms");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Hareketler", b =>
                {
                    b.HasOne("EntityLayer.Concrete.Firmalar", "Firmalar")
                        .WithMany("Hareketlers")
                        .HasForeignKey("FirmalarFirmaID");

                    b.HasOne("EntityLayer.Concrete.Oyunlar", "Oyunlar")
                        .WithMany("Hareketlers")
                        .HasForeignKey("OyunlarOyunID");

                    b.HasOne("EntityLayer.Concrete.Platform", "Platform")
                        .WithMany("Hareketlers")
                        .HasForeignKey("Platformid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Firmalar");

                    b.Navigation("Oyunlar");

                    b.Navigation("Platform");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Oyunlar", b =>
                {
                    b.HasOne("EntityLayer.Concrete.Category", "Category")
                        .WithMany("Oyunlars")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityLayer.Concrete.Platform", "Platform")
                        .WithMany("Oyunlars")
                        .HasForeignKey("Platformid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Platform");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Category", b =>
                {
                    b.Navigation("Oyunlars");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Firmalar", b =>
                {
                    b.Navigation("Hareketlers");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Oyunlar", b =>
                {
                    b.Navigation("Hareketlers");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Platform", b =>
                {
                    b.Navigation("Hareketlers");

                    b.Navigation("Oyunlars");
                });
#pragma warning restore 612, 618
        }
    }
}
